'use strict';
const http=require('http'),fs=require('fs'),path=require('path');
const PORT=Number(process.env.PORT||3000);
const TOKEN=String(process.env.PLAY_TOKEN||'').trim();
if(!/^[A-Za-z0-9_-]{32,}$/.test(TOKEN)){console.error('PLAY_TOKEN is missing or invalid');process.exit(1);}
const SITE=path.join(__dirname,'site'),PREFIX=`/play/${TOKEN}`;
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon','.wav':'audio/wav','.mp3':'audio/mpeg','.woff2':'font/woff2'};
function headers(res,type='text/plain; charset=utf-8'){res.setHeader('Content-Type',type);res.setHeader('Cache-Control','private, no-store, max-age=0, must-revalidate');res.setHeader('Pragma','no-cache');res.setHeader('Expires','0');res.setHeader('X-Robots-Tag','noindex, nofollow, noarchive, nosnippet, noimageindex');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Resource-Policy','same-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=(), payment=(), usb=(), bluetooth=(), serial=(), hid=(), clipboard-read=(), browsing-topics=()');res.setHeader('Content-Security-Policy',"default-src 'self'; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; form-action 'none'; connect-src 'none'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; media-src 'self' data: blob:; font-src 'self' data:; worker-src 'none'; manifest-src 'none'");res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');}
function deny(res){headers(res);res.statusCode=404;res.end('Not Found');}
function send(req,res,file){fs.stat(file,(e,st)=>{if(e||!st.isFile())return deny(res);headers(res,MIME[path.extname(file).toLowerCase()]||'application/octet-stream');res.statusCode=200;res.setHeader('Content-Length',st.size);if(req.method==='HEAD')return res.end();const s=fs.createReadStream(file);s.on('error',()=>res.destroy());s.pipe(res);});}
http.createServer((req,res)=>{if(req.method!=='GET'&&req.method!=='HEAD'){headers(res);res.statusCode=405;return res.end('Method Not Allowed');}let p;try{p=decodeURIComponent(new URL(req.url,'http://localhost').pathname);}catch{return deny(res);}if(p===PREFIX){headers(res);res.statusCode=308;res.setHeader('Location',PREFIX+'/');return res.end();}if(p===PREFIX+'/')return send(req,res,path.join(SITE,'index.html'));if(!p.startsWith(PREFIX+'/'))return deny(res);const rel=p.slice(PREFIX.length+1);if(!rel||rel.includes('\0'))return deny(res);const norm=path.posix.normalize('/'+rel).slice(1);if(norm.startsWith('..')||norm.includes('/../'))return deny(res);const file=path.join(SITE,norm),r=path.relative(SITE,file);if(r.startsWith('..')||path.isAbsolute(r))return deny(res);send(req,res,file);}).listen(PORT,'0.0.0.0',()=>console.log('Playtest service listening'));
